transforms:
  - name: column_transform_chain
    config:
      transforms:
        - name: norm_numeric
          config:
            use_skew_threshold: true
  - name: griffin_feature_split_column
    config:
      keep_original_columns: true
      allow_no_template: true
  - name: column_transform_chain
    config:
      transforms:
        # - name: compute_category_num
        - name: remap_category
          config:
            with_category_mapping: true